version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"

  dotametaexplorer:
    build:
      context: ./DotaMetaExplorer
      dockerfile: Dockerfile
    container_name: dota-meta-explorer
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "8080:8080"
    depends_on:
      - db

  telegrambot:
    build:
      context: .
      dockerfile: TelegramBot/Dockerfile
    container_name: telegrambot
    depends_on:
      - dotametaexplorer