# .github/workflows/ci.yaml

name: CI Build, Test & Push Docker Images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore 

      - name: Build solution
        run: dotnet build --configuration Release --no-restore 

      - name: Run all tests
        run: dotnet test --configuration Release --no-build --verbosity normal 

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Docker image (DotaMetaExplorer)
        if: github.event_name != 'pull_request'
        run: |
          docker build \
            -t dotestry/dotameta:latest \
            -t dotestry/dotameta:${{ github.sha }} \
            -f DotaMetaExplorer/Dockerfile \
            ./DotaMetaExplorer 
          docker push dotestry/dotameta:latest
          docker push dotestry/dotameta:${{ github.sha }}

      - name: Build and push Telegram Bot Docker image
        if: github.event_name != 'pull_request'
        run: |
          docker build \
            -t dotestry/dotatelegrambot:latest \
            -t dotestry/dotatelegrambot:${{ github.sha }} \
            -f TelegramBot/Dockerfile \
            .  
          docker push dotestry/dotatelegrambot:latest
          docker push dotestry/dotatelegrambot:${{ github.sha }}